### ISSUE TITLE
Breaks on Windows

### ISSUE THREAD

**Issue by overengineer** [BenjaminRi/Case-Sensitive#1]
This repository breaks on Windows due to case insensitivity.

**Comment by BenjaminRi** [comment]
Thank you for your bug report. Please forward this problem to Microsoft such that the issue can be fixed upstream. In the meantime, I recommend you use the Windows Subsystem for Linux (WSL) or replace your operating system with one that has a file system that does not exhibit this bug, like Linux.

**Comment by artemiswkearney** [comment]
Workaround: create a [case-sensitive folder](https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity) and clone the repo into it. Make sure your Git install is also configured to be case sensitive.

**Comment by BenjaminRi** [comment]
Over the course of the day, we contacted our community members and to our surprise, there is a substantial Windows user base. These people have been silently working around the problem until @overengineer made us aware of the issue. Because the interest in a Windows version is so large, we deliberated how we could both preserve this repository's original purpose and satisfy the needs of our Windows users. We are proud to announce that starting today, we maintain the [windows-compat](https://github.com/BenjaminRi/Case-Sensitive/tree/windows-compat) branch which is dedicated to our loyal Windows users who have been suffering silently thus far. The [windows-compat](https://github.com/BenjaminRi/Case-Sensitive/tree/windows-compat) branch will always be kept up to date with the latest developments and bug fixes on `master`, hence our Windows users are no longer facing breakage during checkout while enjoying the latest version of our software. We hope this resolves your problem and wish you a pleasant day :rocket:
